# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Digest-SHA1
version:      0.03
version_from: SHA1.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    Template:                      2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
